replicaCount: 1

image:
  repository: ghcr.io/kaigents/kaigents-operator
  pullPolicy: IfNotPresent
  tag: ""

runnerImage:
  repository: ghcr.io/kaigents/kaigents-runner
  pullPolicy: IfNotPresent
  tag: ""

runnerEnv:
  []

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

runnerServiceAccount:
  create: true
  name: kaigents-runner

rbac:
  create: true

leaderElection:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
